version: '3'
services:
  zookeeper:
   image: dock.gaikai.org/qnib/plain-zookeeper:latest-rev9
   ports:
     - "2181:2181"
  zkui:
    image: qnib/plain-zkui
    ports:
      - "9090:9090"
    environment:
      ZK_SERVER: "zookeeper:2181"
  broker:
    image: dock.gaikai.org/qnib/plain-kafka:latest-rev11
    ports:
     - "9092:9092"
    environment:
      ADVERTISED_LISTENERS: "localhost:9092"
      ZK_SERVERS: "zookeeper"

